export const POETIC_CYCLES = ['night', 'dawn', 'morning', 'day', 'twilight'];

export const poeticNodes = [
  {
    id: 'dawn-mist',
    fragment: "Brume d'aube sur la tasse",
    meter: 5,
    aroma: 'brume azurée',
    tone: 'calme',
    cluster: 'Aurore spirale',
    entry: true,
    cycles: ['dawn', 'morning', 'twilight'],
    textures: ['rosée', 'vapeur'],
  },
  {
    id: 'quartz-steam',
    fragment: 'Quartz solaire réchauffe les mains',
    meter: 7,
    aroma: 'zeste solaire',
    tone: 'tonique',
    cluster: 'Aurore spirale',
    entry: false,
    cycles: ['morning', 'day'],
    textures: ['chaleur', 'lumière'],
  },
  {
    id: 'herbal-veil',
    fragment: 'Voile d’herbes sur la pulpe',
    meter: 5,
    aroma: 'menthe douce',
    tone: 'herboriste',
    cluster: 'Feuilles voyageuses',
    entry: true,
    cycles: ['dawn', 'day'],
    textures: ['feuillage', 'brise'],
  },
  {
    id: 'azure-spark',
    fragment: 'Étincelle azur dans la vapeur',
    meter: 7,
    aroma: 'ozone léger',
    tone: 'étincelant',
    cluster: 'Feuilles voyageuses',
    entry: false,
    cycles: ['morning', 'day', 'twilight'],
    textures: ['lumière', 'électricité'],
  },
  {
    id: 'lunar-honey',
    fragment: 'Miel lunaire sur la langue',
    meter: 5,
    aroma: 'douceur nocturne',
    tone: 'velouté',
    cluster: 'Nuit carmin',
    entry: true,
    cycles: ['night', 'twilight'],
    textures: ['velours', 'succulence'],
  },
  {
    id: 'nebula-silk',
    fragment: 'Soie nébuleuse enlace le souffle',
    meter: 7,
    aroma: 'iris cosmique',
    tone: 'aérien',
    cluster: 'Nuit carmin',
    entry: false,
    cycles: ['night', 'dawn'],
    textures: ['brume', 'lueur'],
  },
  {
    id: 'petal-ember',
    fragment: 'Braise de pétales sous la paume',
    meter: 5,
    aroma: 'rose fumée',
    tone: 'ardent',
    cluster: 'Flamme florale',
    entry: false,
    cycles: ['day', 'twilight'],
    textures: ['pétale', 'braise'],
  },
  {
    id: 'crystal-rain',
    fragment: 'Pluie cristalline suit la pulsation',
    meter: 7,
    aroma: 'cascade tonique',
    tone: 'fluide',
    cluster: 'Flamme florale',
    entry: false,
    cycles: ['day', 'twilight'],
    textures: ['gouttes', 'miroirs'],
  },
  {
    id: 'solstice-heart',
    fragment: 'Cœur de solstice bat la cendre',
    meter: 5,
    aroma: 'bois doré',
    tone: 'solaire',
    cluster: 'Spirale du temps',
    entry: false,
    cycles: ['day', 'twilight'],
    textures: ['bois', 'battement'],
  },
  {
    id: 'orbit-breeze',
    fragment: 'Brise d’orbite danse en houle',
    meter: 7,
    aroma: 'sel astral',
    tone: 'marin',
    cluster: 'Spirale du temps',
    entry: false,
    cycles: ['day', 'twilight', 'night'],
    textures: ['sel', 'vent'],
  },
  {
    id: 'aurora-knot',
    fragment: 'Nœud d’aurore serre les fibres',
    meter: 5,
    aroma: 'pollen de ciel',
    tone: 'vibrant',
    cluster: 'Aurore spirale',
    entry: false,
    cycles: ['dawn', 'twilight', 'night'],
    textures: ['rubans', 'halo'],
  },
  {
    id: 'ember-lullaby',
    fragment: 'Berceuse de braise apaise le vide',
    meter: 7,
    aroma: 'ambre lent',
    tone: 'apaisant',
    cluster: 'Nuit carmin',
    entry: false,
    cycles: ['night'],
    textures: ['chaleur', 'chant'],
  },
  {
    id: 'tide-memory',
    fragment: 'Mémoire de marée dans la tasse',
    meter: 5,
    aroma: 'écume saline',
    tone: 'nostalgique',
    cluster: 'Spirale du temps',
    entry: true,
    cycles: ['day', 'twilight', 'night'],
    textures: ['vagues', 'mémoire'],
  },
  {
    id: 'shadow-tea',
    fragment: 'Thé d’ombre veille la veine',
    meter: 7,
    aroma: 'fumée d’encre',
    tone: 'mystérieux',
    cluster: 'Nuit carmin',
    entry: false,
    cycles: ['night', 'dawn'],
    textures: ['ombre', 'respiration'],
  },
];

export const poeticEdges = {
  'dawn-mist': [
    {
      target: 'quartz-steam',
      weight: 0.92,
      transition: "La brume s'étire en rayon",
      aroma: 'zeste lumineux',
      cycles: ['dawn', 'morning'],
    },
    {
      target: 'herbal-veil',
      weight: 0.78,
      transition: 'Les herbes s’ouvrent dans la rosée',
      aroma: 'menthe givrée',
      cycles: ['dawn', 'morning', 'day'],
    },
    {
      target: 'aurora-knot',
      weight: 0.66,
      transition: 'Un ruban de ciel se noue',
      aroma: 'halo sucré',
      cycles: ['dawn', 'twilight'],
    },
  ],
  'quartz-steam': [
    {
      target: 'azure-spark',
      weight: 0.88,
      transition: 'Le quartz se diffracte en éclats',
      aroma: 'pomme givrante',
      cycles: ['morning', 'day'],
    },
    {
      target: 'petal-ember',
      weight: 0.74,
      transition: 'La chaleur devient braise florale',
      aroma: 'rose solaire',
      cycles: ['day', 'twilight'],
    },
  ],
  'herbal-veil': [
    {
      target: 'azure-spark',
      weight: 0.81,
      transition: 'Les feuilles se teintent d’azur',
      aroma: 'pluie électrique',
      cycles: ['morning', 'day'],
    },
    {
      target: 'nebula-silk',
      weight: 0.72,
      transition: 'Les herbes se dissipent en soie',
      aroma: 'iris nocturne',
      cycles: ['twilight', 'night'],
    },
    {
      target: 'solstice-heart',
      weight: 0.69,
      transition: 'Le cœur de bois s embrase',
      aroma: 'écorce sucrée',
      cycles: ['day', 'twilight'],
    },
  ],
  'azure-spark': [
    {
      target: 'petal-ember',
      weight: 0.83,
      transition: 'L étincelle attise les pétales',
      aroma: 'braise florale',
      cycles: ['day', 'twilight'],
    },
    {
      target: 'orbit-breeze',
      weight: 0.7,
      transition: 'La lumière file vers la houle',
      aroma: 'sel doux',
      cycles: ['day', 'twilight'],
    },
    {
      target: 'aurora-knot',
      weight: 0.68,
      transition: 'Les ions se tressent en aurore',
      aroma: 'miel polaire',
      cycles: ['dawn', 'twilight'],
    },
  ],
  'lunar-honey': [
    {
      target: 'nebula-silk',
      weight: 0.86,
      transition: 'La douceur se dilue en brume',
      aroma: 'pollen astral',
      cycles: ['night', 'dawn'],
    },
    {
      target: 'tide-memory',
      weight: 0.73,
      transition: 'La lune appelle la marée',
      aroma: 'sel de miel',
      cycles: ['night', 'twilight'],
    },
    {
      target: 'ember-lullaby',
      weight: 0.77,
      transition: 'La tiédeur devient chant',
      aroma: 'ambre cotonneux',
      cycles: ['night'],
    },
  ],
  'nebula-silk': [
    {
      target: 'petal-ember',
      weight: 0.67,
      transition: 'La soie ranime les braises',
      aroma: 'iris fumé',
      cycles: ['twilight', 'night'],
    },
    {
      target: 'shadow-tea',
      weight: 0.75,
      transition: 'La brume se condense en encre',
      aroma: 'fumée irisée',
      cycles: ['night', 'dawn'],
    },
    {
      target: 'aurora-knot',
      weight: 0.7,
      transition: 'Les filaments rejoignent l aurore',
      aroma: 'sucre stellaire',
      cycles: ['dawn', 'twilight'],
    },
  ],
  'petal-ember': [
    {
      target: 'crystal-rain',
      weight: 0.82,
      transition: 'Les braises éclatent en pluie claire',
      aroma: 'pivoine saline',
      cycles: ['day', 'twilight'],
    },
    {
      target: 'solstice-heart',
      weight: 0.78,
      transition: 'La fleur révèle le bois doré',
      aroma: 'résine rose',
      cycles: ['day', 'twilight'],
    },
  ],
  'crystal-rain': [
    {
      target: 'orbit-breeze',
      weight: 0.76,
      transition: 'Les gouttes deviennent houle',
      aroma: 'océan givré',
      cycles: ['day', 'twilight'],
    },
    {
      target: 'tide-memory',
      weight: 0.71,
      transition: 'La pluie rejoint la mémoire',
      aroma: 'écume ambrée',
      cycles: ['twilight', 'night'],
    },
  ],
  'solstice-heart': [
    {
      target: 'orbit-breeze',
      weight: 0.79,
      transition: 'Le cœur solaire déclenche la houle',
      aroma: 'bois marin',
      cycles: ['day', 'twilight'],
    },
    {
      target: 'aurora-knot',
      weight: 0.74,
      transition: 'Les braises gravent une aurore',
      aroma: 'miel boisé',
      cycles: ['twilight', 'night'],
    },
    {
      target: 'tide-memory',
      weight: 0.68,
      transition: 'Le solstice se fond en marée',
      aroma: 'sel doux',
      cycles: ['day', 'twilight'],
    },
  ],
  'orbit-breeze': [
    {
      target: 'aurora-knot',
      weight: 0.72,
      transition: 'La houle tresse une aurore',
      aroma: 'embruns sucrés',
      cycles: ['twilight', 'night'],
    },
    {
      target: 'shadow-tea',
      weight: 0.7,
      transition: 'Le vent retombe en ombre',
      aroma: 'algue fumée',
      cycles: ['night'],
    },
  ],
  'aurora-knot': [
    {
      target: 'ember-lullaby',
      weight: 0.69,
      transition: 'Le nœud irradie un chant lent',
      aroma: 'pollen chaud',
      cycles: ['twilight', 'night'],
    },
    {
      target: 'tide-memory',
      weight: 0.71,
      transition: 'Les rubans rejoignent la marée',
      aroma: 'sel polaire',
      cycles: ['night'],
    },
    {
      target: 'quartz-steam',
      weight: 0.64,
      transition: 'Les rubans réveillent le quartz',
      aroma: 'givre doux',
      cycles: ['dawn'],
    },
  ],
  'ember-lullaby': [
    {
      target: 'shadow-tea',
      weight: 0.8,
      transition: 'La berceuse se décante en ombre',
      aroma: 'cendre vanillée',
      cycles: ['night'],
    },
    {
      target: 'lunar-honey',
      weight: 0.7,
      transition: 'Le chant retourne au miel',
      aroma: 'ambre perlée',
      cycles: ['night', 'dawn'],
    },
  ],
  'tide-memory': [
    {
      target: 'shadow-tea',
      weight: 0.76,
      transition: 'La marée plonge dans l’encre',
      aroma: 'sel enfumé',
      cycles: ['night'],
    },
    {
      target: 'dawn-mist',
      weight: 0.7,
      transition: 'La mémoire se dissout en brume',
      aroma: 'rosée saline',
      cycles: ['dawn'],
    },
    {
      target: 'crystal-rain',
      weight: 0.67,
      transition: 'Les vagues nourrissent la pluie',
      aroma: 'cascade marine',
      cycles: ['day', 'twilight'],
    },
  ],
  'shadow-tea': [
    {
      target: 'dawn-mist',
      weight: 0.74,
      transition: 'L’ombre rend la brume au matin',
      aroma: 'fumée claire',
      cycles: ['dawn'],
    },
    {
      target: 'lunar-honey',
      weight: 0.78,
      transition: 'L’ombre s’adoucit en miel',
      aroma: 'résine nocturne',
      cycles: ['night'],
    },
  ],
};
